spring:
   datasource:
    username: root
    password: a
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/digitalmall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false

   mvc:
     view:
       prefix: WEB-INF/jsp/
       suffix: .jsp

   mail:
      #邮件服务地址
      host: smtp.163.com
      #用户名
      username: q1156295142@163.com
      #授权码
      password: x19980617
      #编码
      default-encoding: UTF-8

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: cn.xyz.entity

mail.fromMail.addr: q1156295142@163.com
